name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - template: ci/stages/quality_checks.yaml
    parameters:
      charts:
        demo: $(System.DefaultWorkingDirectory)/charts/demo
      failWithVuln: false
